export const metadata = {
  title: 'my-app',
  description: 'Generated by Next.js <>',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header 
          style={{
            backgroundColor: 'lightblue',
            padding: '1rem',
          }}  
        >
          <p>Header</p>
        </header>

        <div className="main">
          {children}
        </div>
        
        
        <footer
          style={{
            backgroundColor: 'ghostwhite',
            padding: '1rem',
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
